import type { EffectPreset } from "./types";

export const BUILTIN_PRESETS: EffectPreset[] = [
  {
    id: "preset-christmas-classic",
    name: "Christmas Classic",
    effectType: "wash",
    parameters: { color1: "#cc0000", color2: "#006600", intensity: 0.8, speed: 0.3, easing: "ease-in-out" },
    version: 1,
    compatibleFixtureTypes: ["roofline", "bush", "window-outline", "arch"],
    tags: ["color", "holiday"],
    createdAt: "2026-01-01T00:00:00Z",
    isSystem: true,
  },
  {
    id: "preset-snow-storm",
    name: "Snow Storm",
    effectType: "twinkle",
    parameters: { color1: "#ffffff", intensity: 0.9, speed: 0.7, density: 0.8, easing: "linear" },
    version: 1,
    compatibleFixtureTypes: ["roofline", "mega-tree", "mini-tree", "bush", "arch", "window-outline"],
    tags: ["texture", "holiday"],
    createdAt: "2026-01-01T00:00:00Z",
    isSystem: true,
  },
  {
    id: "preset-chase-red",
    name: "Chase Red",
    effectType: "chase",
    parameters: { color1: "#ff0000", intensity: 1.0, speed: 0.6, direction: "forward", easing: "linear" },
    version: 1,
    compatibleFixtureTypes: ["roofline", "arch"],
    tags: ["motion"],
    createdAt: "2026-01-01T00:00:00Z",
    isSystem: true,
  },
  {
    id: "preset-strobe-white",
    name: "Strobe White",
    effectType: "strobe",
    parameters: { color1: "#ffffff", intensity: 1.0, speed: 0.9, easing: "linear" },
    version: 1,
    compatibleFixtureTypes: ["roofline", "mega-tree", "mini-tree", "bush", "arch", "window-outline"],
    tags: ["texture"],
    createdAt: "2026-01-01T00:00:00Z",
    isSystem: true,
  },
  {
    id: "preset-warm-fade",
    name: "Warm Fade",
    effectType: "fade",
    parameters: { color1: "#ffcc66", intensity: 0.7, speed: 0.2, easing: "ease-in-out" },
    version: 1,
    compatibleFixtureTypes: ["roofline", "window-outline", "bush"],
    tags: ["color", "holiday"],
    createdAt: "2026-01-01T00:00:00Z",
    isSystem: true,
  },
  {
    id: "preset-rainbow-sweep",
    name: "Rainbow Sweep",
    effectType: "wave",
    parameters: { color1: "#ff0000", color2: "#0000ff", intensity: 0.85, speed: 0.5, easing: "linear" },
    version: 1,
    compatibleFixtureTypes: ["roofline", "mega-tree", "arch"],
    tags: ["color", "motion"],
    createdAt: "2026-01-01T00:00:00Z",
    isSystem: true,
  },
];
